services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guerra_das_metas_app
    ports:
      - "9002:3000"
    volumes:
      - ./guerra_das_metas.db:/app/guerra_das_metas.db
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    user: "1000:1000"
